服务发现推空保护
polarismesh/polaris-java pull request #141
Opened 2022-05-28 09:05 UTC by gongzhijian

feat:服务发现推空保护，日志修复

2022-05-28 09:06 UTC, gongzhijian commented
帮忙审核一下，谢谢

2022-05-28 09:20 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
> +        Configuration configuration = ConfigAPIFactory.defaultConfig();
这里推空的开关应该由 InMemoryRegistry 传进来，并且需要确保，如果这里 setValue 没有真正操作的话，那么下面的 CacheUpdate 动作也不应该执行

2022-05-28 09:20 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
> +        Configuration configuration = ConfigAPIFactory.defaultConfig();
ConfigAPIFactory.defaultConfig() 是给使用者用的，可以看下别的插件的相关配置是如何初始化的

2022-05-28 09:21 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
> +        Configuration configuration = ConfigAPIFactory.defaultConfig();
可以参考这里的实现：https://github.com/gongzhijian/polaris-java/blob/58b4a145786b3e9dad30fd154e73b93ebd518edd/polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/InMemoryRegistry.java#L441

2022-05-28 09:27 UTC, gongzhijian commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
> +        Configuration configuration = ConfigAPIFactory.defaultConfig();
好的，我重新看一下

2022-05-31 02:27 UTC, lepdou approved these changes
LGTM

2022-05-31 02:30 UTC, SkyeBeFreeman requested changes

2022-05-31 02:30 UTC, SkyeBeFreeman commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
> +        ServiceInstancesByProto instances = (ServiceInstancesByProto) registryCacheValue;
需要判断是否能够强制类型转换

2022-05-31 02:50 UTC, SkyeBeFreeman commented
@gongzhijian run and pass all the junit test before pushing your commit. Plz check the [Action](https://github.com/polarismesh/polaris-java/runs/6663559003?check_suite_focus=true).

2022-05-31 02:55 UTC, lepdou commented on polaris-common/polaris-config-default/src/main/resources/conf/default-config.yml
> +    pushEmptyProtection: false
默认值设置为 true 比较好？

有以下两个点的考虑：
1. 大部分用户不知道有这个开关，所以基本上很少有人去一开始想着打开开关，只有在故障发生之后，才会去查有没有开关。
2. 推空保护还是非常重要的，在有些故障场景下是最后一道防线。

2022-05-31 02:57 UTC, gongzhijian commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
> +        ServiceInstancesByProto instances = (ServiceInstancesByProto) registryCacheValue;
好的，我稍微调整一下

2022-05-31 02:59 UTC, gongzhijian commented on polaris-common/polaris-config-default/src/main/resources/conf/default-config.yml
> +    pushEmptyProtection: false
好的，我调整一下

2022-06-01 08:16 UTC, SkyeBeFreeman requested changes

2022-06-01 08:16 UTC, SkyeBeFreeman commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
>          value.set(registryCacheValue);
无论是否推空保护，这里都会设置成新值？同时，建议在多注册多发现场景下进行回归验证

2022-06-01 08:25 UTC, gongzhijian commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
>          value.set(registryCacheValue);
这里放错位置了，这里推送数据为空的时候，不设置的话，后面的数据更改的也不用执行，刚在解决冲突，把这个给搞漏掉了，我再调整一下

2022-06-01 08:42 UTC, gongzhijian commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
>          value.set(registryCacheValue);
设置的动作，我放到后面了

2022-06-01 08:46 UTC, SkyeBeFreeman requested changes

2022-06-01 08:46 UTC, SkyeBeFreeman commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
> +        LOG.info("CacheObject: value for {} is updated, revision {}", svcEventKey, registryCacheValue.getRevision());
这里的revision应该打印originRevision还是registryCacheValue.getRevision()，需要解释一下

2022-06-01 09:41 UTC, gongzhijian commented on polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
> +        LOG.info("CacheObject: value for {} is updated, revision {}", svcEventKey, registryCacheValue.getRevision());
这里的revision应该视情况来定，如果传过来的revision存在的话，就用传过来的，不存在，用缓存的。

2022-06-01 10:32 UTC, SkyeBeFreeman approved these changes
LGTM.

2022-06-01 11:07 UTC, SkyeBeFreeman commented
@gongzhijian Plz check the junit test. https://github.com/polarismesh/polaris-java/actions

2022-06-02 10:01 UTC, merged