Add nacos connector plugin support .
polarismesh/polaris-java pull request #143
Opened 2022-06-07 03:44 UTC by misselvexu

## PR Type
Feature.

## Describe what this PR does for and how you did.
Add nacos connector plugin support .

## Does this PR be associated with issue? If so, please adding the issue link below.
ISSUES #131 

## Note
none .

### Checklist
- [x] Code compiles correctly
- [ ] Create at least one junit test if possible
- [x] All tests passing
- [x] Extend documentation if necessary
- [ ] Add myself / the copyright holder to the AUTHORS file

2022-06-17 11:33 UTC, SkyeBeFreeman requested changes
`com.tencent.polaris.plugins.connector.composite.CompositeServiceUpdateTask#notifyServerEvent`内需要考虑多数据源合并去重，例如同时注册与发现consul和nacos.

2022-06-17 11:33 UTC, SkyeBeFreeman commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        // do nothing
Why not implement heartbeat?

2022-06-17 13:22 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        // do nothing
nacos没有让用户自己上报心跳的接口

2022-06-17 14:05 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +            return new ServiceInstancesResponse("NaN", instanceList);
这里为什么要是NaN ？

2022-06-17 14:05 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +    public Services syncGetServices(ServiceUpdateTask serviceUpdateTask) {
获取服务有专门的接口：[getServicesOfServer](https://github.com/alibaba/nacos/blob/b584531331cc95054964ba4e33984f4cab9e582d/client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java#L422)

2022-06-17 14:05 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +                    DEFAULT_GROUP, Lists.newArrayList(DEFAULT_CLUSTER_NAME));
这里写死不太好，并且也不要设置 Cluster 信息，Group 的信息最好看下可以从哪里透传设置下，这两个参数不要写死

2022-06-17 14:12 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +                String instanceId = String.format(INSTANCE_NAME, req.getService(), req.getHost(), req.getPort());
还要加上命名空间

2022-06-17 14:12 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        String address = config.getAddresses().get(0);
对于nacos来说，最好看看能不能支持下设置命名空间吧，不然默认都在public，不太好

2022-06-17 14:12 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        CommonProviderResponse response = new CommonProviderResponse();
nacos这里不支持一个客户端注册到多个namespace中去，需要考虑怎么处理，是做限制，还是做兼容

2022-06-17 14:12 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +    public ServiceInstancesResponse syncGetServiceInstances(ServiceUpdateTask serviceUpdateTask) {
这个只能查询默认命名空间下的服务实例数据信息，如果多命名空间就会有问题，这里需要考虑怎么处理

2022-06-17 14:25 UTC, misselvexu commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        String address = config.getAddresses().get(0);
Got it，
Consider redesigning the URL of the connection for nacos connector 。

2022-06-20 03:49 UTC, misselvexu commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +            List<ServerConnectorConfigImpl> serverConnectorConfigs = ctx.getConfig().getGlobal().getServerConnectors();
> 这一块逻辑后续应该统一优化一下，应该每个ServerConnector只能关心到自己的Configuration

During the initialization of `CompositeConnector#init(InitContext)`, the corresponding configuration is distributed according to the `Plugin#getName()` type ?

2022-06-20 04:05 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +            List<ServerConnectorConfigImpl> serverConnectorConfigs = ctx.getConfig().getGlobal().getServerConnectors();
optimization can be considered later

2022-06-20 05:45 UTC, misselvexu commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        CommonProviderResponse response = new CommonProviderResponse();
Is it possible to map Polaris' `namespace` to Nacos' concept of `group` ?

2022-06-20 05:45 UTC, misselvexu commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        CommonProviderResponse response = new CommonProviderResponse();
> nacos这里不支持一个客户端注册到多个namespace中去，需要考虑怎么处理，是做限制，还是做兼容

Is it possible to map Polaris' `namespace` to Nacos' concept of `group` ?

2022-06-20 06:24 UTC, misselvexu commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +            List<ServerConnectorConfigImpl> serverConnectorConfigs = ctx.getConfig().getGlobal().getServerConnectors();
> optimization can be considered later

Copy that.

2022-06-20 06:27 UTC, chuntaojun requested changes

2022-06-20 06:27 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +                instance.setPort(service.getPort());
Why are attributes such as metadata not synchronized here?

2022-06-20 06:27 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +    public Services syncGetServices(ServiceUpdateTask serviceUpdateTask) {
这不是一个好的获取方式，建议使用专有接口进行获取

2022-07-26 02:59 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        CommonProviderResponse response = new CommonProviderResponse();
还是不要这样子，建议nacos的connector，一个connector就对应一个namespace，如果有多个的话，那就注册多个connector吧

2022-09-14 02:45 UTC, lepdou approved these changes

2022-09-14 02:45 UTC, lepdou commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        String address = config.getAddresses().get(0);
命名空间的配置，应该还是要兼容nacos原有的配置？

2022-09-14 02:45 UTC, lepdou commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        CommonProviderResponse response = new CommonProviderResponse();
nacos 的 模型里，一个进程只属于一个namespace。所以没必要支持nacos多namespace把？

2022-09-14 02:45 UTC, lepdou commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +    public ServiceInstancesResponse syncGetServiceInstances(ServiceUpdateTask serviceUpdateTask) {
没必要支持多命名空间？跟nacos的行为保持一致。当然也不能查询默认命名空间，应该还是需要解析用户的nacos配置，获取到用户指定的命名空间。

2022-09-14 09:52 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +                    properties.put(PropertyKeyConst.NAMESPACE, "default");
没有就不是 default 这里，参考nacos的默认行为处理，否则会导致在nacos页面上看不到注册的服务实例

2022-09-14 09:52 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +  public static void main(String[] args) {
为啥这里会有一个 main ？

2022-09-14 09:52 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +            return new ServiceInstancesResponse(String.valueOf(System.currentTimeMillis()), instanceList);
这里的实现我觉得可以在调整下，nacos本身有一个watch的能力，我理解应该去watch 这个服务，然后单独一个 map 去维护这个，那这里也不会频繁出现 revision 变动导致上层实例的计算不断出现 refresh

2022-09-14 09:52 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +                instance.setIsolated(service.isEphemeral());
这个不对，是 service.isEnable()

2022-09-14 09:52 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        this.registerInstance(req);
不要做这个事情，这里就是 //do nothing

2022-09-14 10:47 UTC, misselvexu commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +            return new ServiceInstancesResponse(String.valueOf(System.currentTimeMillis()), instanceList);
ok, let me think think ...

2022-09-14 10:53 UTC, misselvexu commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +                instance.setIsolated(service.isEphemeral());
> 这个不对，是 service.isEnable()

What is the purpose of this field `isolated`?

2022-09-14 10:58 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +                instance.setIsolated(service.isEphemeral());
保持实例在运行的情况下，将实例进行摘除，可以用于线上故障实例快速隔离，然后保留现场排查问题

2022-09-15 02:17 UTC, chuntaojun requested changes

2022-09-15 02:17 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +                    properties.put(PropertyKeyConst.NAMESPACE, "public");
这里不对，如果没有设置命名空间，properties里面就不要设置 PropertyKeyConst.NAMESPACE，参考 nacos 那边的默认使用方式：https://nacos.io/zh-cn/docs/sdk.html

2022-10-19 09:51 UTC, andrewshan commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        CommonProviderResponse response = new CommonProviderResponse();
还是一个connector吧，在一个connector中支持多命名空间，通过map进行ns到NamingService的索引，可以参考这里的实现：https://github.com/polarismesh/polaris-sync/blob/main/polaris-sync-registry-plugins/registry-nacos/src/main/java/cn/polarismesh/polaris/sync/registry/plugins/nacos/NacosRegistryCenter.java

2022-10-19 09:53 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java
> +        CommonProviderResponse response = new CommonProviderResponse();
我之前说的一个ns对应一个 connector 可能有点问题，或许需要一个NacosConnector，这个NacosConnector里面有一个Map<Ns, NacosClient>，从而支持多ns

2022-10-24 06:58 UTC, chuntaojun approved these changes

2022-10-24 07:18 UTC, merged