feat: add create api by addresses
polarismesh/polaris-java pull request #148
Opened 2022-06-09 05:27 UTC by huyuanxin

#147

2022-06-09 07:50 UTC, SkyeBeFreeman requested changes

2022-06-09 07:50 UTC, SkyeBeFreeman commented on polaris-discovery/polaris-discovery-factory/src/main/java/com/tencent/polaris/factory/api/DiscoveryAPIFactory.java
> +        ConfigurationImpl configuration = new ConfigurationImpl("");
使用这种方式创建Configuration是否更好？
```java
Configuration configuration = ConfigAPIFactory.defaultConfig();
```

2022-06-09 07:50 UTC, SkyeBeFreeman commented on polaris-discovery/polaris-discovery-factory/src/main/java/com/tencent/polaris/factory/api/DiscoveryAPIFactory.java
> +        ConfigurationImpl configuration = new ConfigurationImpl("");
使用这种方式创建Configuration是否更好？
```java
Configuration configuration = ConfigAPIFactory.defaultConfig();
```

2022-06-09 08:14 UTC, SkyeBeFreeman commented
建议添加对应的单元测试

2022-06-09 08:26 UTC, huyuanxin commented on polaris-discovery/polaris-discovery-factory/src/main/java/com/tencent/polaris/factory/api/DiscoveryAPIFactory.java
> +        ConfigurationImpl configuration = new ConfigurationImpl("");
ConfigAPIFactory.defaultConfig()返回的是一个顶层Configuration，要进行一个强转，是否可行呢
```java
ConfigurationImpl configuration = (ConfigurationImpl) ConfigAPIFactory.defaultConfig();
```

2022-06-10 02:14 UTC, SkyeBeFreeman requested changes

2022-06-10 02:14 UTC, SkyeBeFreeman commented on polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/ConfigAPIFactory.java
> +        ConfigurationImpl configuration = new ConfigurationImpl("");
直接使用这个创建：
```ConfigurationImpl configuration = (ConfigurationImpl) ConfigAPIFactory.defaultConfig();```

2022-06-16 02:23 UTC, SkyeBeFreeman requested changes

2022-06-16 02:23 UTC, SkyeBeFreeman commented on polaris-discovery/polaris-discovery-factory/src/main/java/com/tencent/polaris/factory/api/DiscoveryAPIFactory.java
> +        ConfigurationImpl configuration = new ConfigurationImpl("");
这里不使用```Configuration configuration = ConfigAPIFactory.createConfigurationByAddress(addressList);```的理由是？

2022-06-16 02:31 UTC, huyuanxin commented on polaris-discovery/polaris-discovery-factory/src/main/java/com/tencent/polaris/factory/api/DiscoveryAPIFactory.java
> +        ConfigurationImpl configuration = new ConfigurationImpl("");
好像是墙住了，没推成功

2022-06-16 02:32 UTC, SkyeBeFreeman commented on polaris-discovery/polaris-discovery-factory/src/main/java/com/tencent/polaris/factory/api/DiscoveryAPIFactory.java
> +        ConfigurationImpl configuration = new ConfigurationImpl("");
ProviderAPI和ConsumerAPI的创建逻辑建议写成同样的形式

2022-06-16 02:47 UTC, SkyeBeFreeman approved these changes
LGTM.

2022-06-16 02:47 UTC, merged