Feat support async register
polarismesh/polaris-java pull request #192
Opened 2022-08-29 06:17 UTC by wallezhang

Support polaris new async register flow.

Close #182

2022-08-30 03:20 UTC, chuntaojun commented on polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/provider/ProviderConfigImpl.java
> +    private final static long DEFAULT_MIN_REGISTER_INTERVAL = 30 * 1000;
空一行

2022-08-30 03:33 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/RegisterStateCache.java
> +        RegisterState registerState = REGISTER_STATES.get(registerStateKey);
可能会有并发问题，建议 computeIfAbsent 之类的语义处理

2022-08-30 03:33 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/RegisterStateCache.java
> +        for (RegisterState registerState : REGISTER_STATES.values()) {
最后清理下这个 Map

2022-08-30 03:35 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/RegisterStateCache.java
> +    private final static Map<String, RegisterState> REGISTER_STATES = new ConcurrentHashMap<>();
这里不建议单例，建议是跟着 SDKContext 生命周期，每个 SDKContext 都有自己的 RegisterStateCache

2022-08-30 03:52 UTC, wallezhang commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/api/DefaultProviderAPI.java
> +    private static final String HEADER_KEY_ASYNC_REGIS = "async-regis";
这里需要统一成什么呢？

2022-08-30 03:53 UTC, wallezhang commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/RegisterStateCache.java
> +    private final static Map<String, RegisterState> REGISTER_STATES = new ConcurrentHashMap<>();
单个应用中可能会有多个SDKContext吗？

2022-08-30 04:04 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/RegisterStateCache.java
> +    private final static Map<String, RegisterState> REGISTER_STATES = new ConcurrentHashMap<>();
你不确定用户会怎么用的，所以还是跟着 SDKContext 来比较好

2022-08-30 04:04 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/api/DefaultProviderAPI.java
> +    private static final String HEADER_KEY_ASYNC_REGIS = "async-regis";
static final 或者 final static，你看看接下来的几行

2022-08-30 04:17 UTC, wallezhang commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/api/DefaultProviderAPI.java
> +    private static final String HEADER_KEY_ASYNC_REGIS = "async-regis";
好的，理解了

2022-08-30 04:17 UTC, wallezhang commented on polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/provider/ProviderConfigImpl.java
> +    private final static long DEFAULT_MIN_REGISTER_INTERVAL = 30 * 1000;
done

2022-08-30 04:17 UTC, wallezhang commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/RegisterStateCache.java
> +    private final static Map<String, RegisterState> REGISTER_STATES = new ConcurrentHashMap<>();
好的，我改一下

2022-08-31 01:13 UTC, chuntaojun requested changes

2022-08-31 01:13 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/RegisterStateManager.java
>      public static void destroy() {
// 根据 SDKContext ID 销毁
destroy(id string)

2022-08-31 03:23 UTC, wallezhang commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/RegisterStateManager.java
>      public static void destroy() {
好的，我修改一下

2022-08-31 09:11 UTC, chuntaojun approved these changes

2022-08-31 09:44 UTC, SkyeBeFreeman commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/core/ProviderAPI.java
> +    InstanceRegisterResponse registerInstance(InstanceRegisterRequest req) throws PolarisException;
方法名改成 `asyncRegister` 可读性会不会更强？

2022-08-31 09:44 UTC, SkyeBeFreeman commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/RegisterStateManager.java
> +        private int heartbeatFailCounter = 0;
是否需要用 `AtomicInteger` ？

2022-08-31 09:44 UTC, SkyeBeFreeman commented on polaris-examples/quickstart-example/quickstart-example-provider/src/main/java/com/tencent/polaris/quickstart/example/Provider.java
> +        InstanceRegisterResponse registerResp = providerAPI.registerInstance(registerRequest);
@chuntaojun 异步服务发现的demo是否应该放在 `polaris-examples/discovery-example` 下？

2022-08-31 10:01 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/core/ProviderAPI.java
> +    InstanceRegisterResponse registerInstance(InstanceRegisterRequest req) throws PolarisException;
这个不应该暴露给用户知道是 asyncRegister 了

2022-08-31 10:02 UTC, chuntaojun commented on polaris-examples/quickstart-example/quickstart-example-provider/src/main/java/com/tencent/polaris/quickstart/example/Provider.java
> +        InstanceRegisterResponse registerResp = providerAPI.registerInstance(registerRequest);
这个SDK来说不是异步，他还是一个同步请求，只不过心的 registerInstance 会帮用户定时做心跳上报的动作

2022-08-31 10:03 UTC, chuntaojun commented on polaris-examples/quickstart-example/quickstart-example-provider/src/main/java/com/tencent/polaris/quickstart/example/Provider.java
> +        InstanceRegisterResponse registerResp = providerAPI.registerInstance(registerRequest);
后续旧的接口也会废弃了，我理解只需要暴露给用户最新的使用就好

2022-08-31 10:03 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/RegisterStateManager.java
> +        private int heartbeatFailCounter = 0;
这里应该不涉及并发？

2022-08-31 10:05 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/AsyncRegisterFlow.java
> +public class AsyncRegisterFlow {
AsyncRegisterFlow => RegisterFlow

2022-08-31 11:07 UTC, SkyeBeFreeman commented on polaris-examples/quickstart-example/quickstart-example-provider/src/main/java/com/tencent/polaris/quickstart/example/Provider.java
> +        InstanceRegisterResponse registerResp = providerAPI.registerInstance(registerRequest);
就以后只用 `registerInstance` 而不是两个选一个是吧？

2022-08-31 14:04 UTC, wallezhang commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/RegisterStateManager.java
> +        private int heartbeatFailCounter = 0;
因为这里只会有一个线程去更新，不存在并发和跨线程访问，所以直接用int即可

2022-08-31 14:04 UTC, wallezhang commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/AsyncRegisterFlow.java
> +public class AsyncRegisterFlow {
done

2022-08-31 14:05 UTC, wallezhang commented on polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/core/ProviderAPI.java
> +    InstanceRegisterResponse registerInstance(InstanceRegisterRequest req) throws PolarisException;
这里参考了go sdk的方法命名

2022-09-01 00:53 UTC, chuntaojun approved these changes

2022-09-01 00:53 UTC, chuntaojun commented on polaris-examples/quickstart-example/quickstart-example-provider/src/main/java/com/tencent/polaris/quickstart/example/Provider.java
> +        InstanceRegisterResponse registerResp = providerAPI.registerInstance(registerRequest);
是的，以后会只留下 registerInstance

2022-09-01 01:36 UTC, SkyeBeFreeman approved these changes

2022-09-01 01:36 UTC, merged