Refactor: Trigger the listener added for the first time
polarismesh/polaris-java pull request #225
Opened 2022-10-13 11:27 UTC by wallezhang

Close issue #183

2022-10-13 12:48 UTC, chuntaojun requested changes

2022-10-13 12:48 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
> +            firstAddedListeners.forEach(
应该先通知，再加入到 listener 中

2022-10-14 02:09 UTC, wallezhang commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
> +            firstAddedListeners.forEach(
这个顺序会有什么影响吗？如果是先通知的话，那需要通过contains方法先判断是否已经在watchers中，然后再通过addAll方法加入

2022-10-14 02:20 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
> +            firstAddedListeners.forEach(
firstAddedListeners 无法保证真的是首次发出去的事件，因为你已经加入到 WatchService了，可能在 firstAddedListeners 开始 notofy 的时候，watchservice 就已经开始做了一次通知

2022-10-14 02:25 UTC, wallezhang commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
> +            firstAddedListeners.forEach(
也就是说，我主动通知的那次，可能已经不是最新的数据，会导致数据不一致的问题吗？

2022-10-14 02:37 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
> +            firstAddedListeners.forEach(
是的

2022-10-14 02:37 UTC, chuntaojun commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
> +            firstAddedListeners.forEach(
最好就是，在加入到 WatchService 之前，就主动 notify 一次

2022-10-14 02:55 UTC, wallezhang commented on polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
> +            firstAddedListeners.forEach(
明白了，我改一下

2022-10-14 08:01 UTC, chuntaojun approved these changes

2022-10-14 08:01 UTC, merged