Add support for config file encryption
polarismesh/polaris-java pull request #404
Opened 2023-06-15 13:17 UTC by fabian4

Related issue: https://github.com/polarismesh/polaris/issues/966

2023-06-21 08:48 UTC, chuntaojun requested changes

2023-06-21 08:48 UTC, chuntaojun commented on polaris-configuration/polaris-configuration-client/src/main/java/com/tencent/polaris/configuration/client/internal/RemoteConfigFileRepo.java
> +    private ConfigFileFilter crypto;
同理，这里获取到的应该是一个 List<ConfigFileFilter>

2023-06-24 13:45 UTC, chuntaojun commented on polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/common/PluginTypes.java
> +    CONFIG_FILTER_CRYPTO(new PluginType(ConfigFileFilter.class, 2)),
CONFIG_FILTER_CRYPTO => CONFIG_FILTER

2023-06-24 13:45 UTC, chuntaojun commented on polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/filter/ConfigFileFilter.java
> +package com.tencent.polaris.api.plugin.filter;
License Header

2023-06-25 07:06 UTC, chuntaojun commented
LGTM

2023-06-28 09:11 UTC, SkyeBeFreeman requested changes
这里是否为默认不开启配置加密功能？

2023-06-28 09:11 UTC, SkyeBeFreeman commented on polaris-configuration/polaris-configuration-client/src/main/java/com/tencent/polaris/configuration/client/internal/ConfigFileManager.java
> +        this.configFileFilters = Collections.singletonList((ConfigFileFilter) sdkContext.getExtensions().getPlugins().getPlugins(PluginTypes.CONFIG_FILTER.getBaseType()));
这里使用singletonList的话，configFileFilters是否还有必要声明为列表？

2023-06-28 09:11 UTC, SkyeBeFreeman commented on polaris-common/polaris-config/src/main/java/com/tencent/polaris/api/config/configuration/CryptoConfig.java
> +
建议校验type的类型，指定类型种类

2023-06-28 09:11 UTC, SkyeBeFreeman commented on polaris-examples/configuration-example/src/main/java/com/tencent/polaris/configuration/example/ConfigFileExample.java
> +//		configFile.addChangeListener(new ConfigFileChangeListener() {
是否可以取消注释？

2023-06-28 09:11 UTC, SkyeBeFreeman commented on polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/java/com/tencent/polaris/plugins/configfilefilter/CryptoConfigFileFilter.java
> +        return "AES";
AES是不是应该体现在类名和依赖名？后面如果有新的加密方式，可以做区别

2023-07-01 02:19 UTC, chuntaojun requested changes

2023-07-01 02:19 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/resources/META-INF/services/com.tencent.polaris.api.plugin.filter.ConfigFileFilter
> +com.tencent.polaris.plugins.configfilefilter.AESCryptoConfigFileFilter
加密拦截器就只有一个CryptoConfigFileFilter，这个 Filter 可以有多种加密算法

2023-07-03 10:17 UTC, chuntaojun requested changes

2023-07-03 10:17 UTC, chuntaojun commented on polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/filter/Crypto.java
> +public interface Crypto extends Plugin {
这里就是定义明确 Encode 和 Decode，public_key 是一个内置的能力，不需要进行插件扩展目前

2023-07-03 10:17 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/java/com/tencent/polaris/plugins/configfilefilter/CryptoConfigFileFilter.java
> +        this.crypto = (Crypto) ctx.getPlugins().getPlugin(PluginTypes.CRYPTO.getBaseType(), cryptoConfig.getType());
这里不对，CryptoConfigFileFilter 里面是可以加载多个 Crypto 实例，根据配置文件返回的算法类型选择对应的 Crypto 进行解密

2023-07-03 12:35 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/java/com/tencent/polaris/plugins/configfilefilter/CryptoConfigFileFilter.java
> +                configFile.setEncrypted(Boolean.TRUE);
这个不是这里设置的，这个是回包收到处理的

2023-07-04 06:42 UTC, fabian4 commented
> 这里是否为默认不开启配置加密功能？

现在支持配置了，需要手动开启

2023-07-11 05:07 UTC, SkyeBeFreeman approved these changes

2023-07-11 05:09 UTC, SkyeBeFreeman requested changes

2023-07-11 05:09 UTC, SkyeBeFreeman commented on polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/java/com/tencent/polaris/plugins/configfilefilter/CryptoConfigFileFilter.java
> +                configFile.setPublicKey(rsaService.getPKCS1PublicKey());
是否应该在解码完成后设置该属性？

2023-07-11 09:58 UTC, fabian4 commented on polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/java/com/tencent/polaris/plugins/configfilefilter/CryptoConfigFileFilter.java
> +                configFile.setPublicKey(rsaService.getPKCS1PublicKey());
目前这个是向服务端请求加密配置的必要参数

2023-07-12 13:47 UTC, chuntaojun requested changes

2023-07-12 13:47 UTC, chuntaojun commented on polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/plugin/PluginConfigImpl.java
> +    public Map<String, Map<?, ?>> getPlugin() {
是不是预防下空指针？

2023-07-12 13:47 UTC, chuntaojun commented on polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/filter/ConfigFileFilterChain.java
> +        if (!enable) {
需要避免空指针，要么就不要用包装类型

2023-07-12 13:47 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/java/com/tencent/polaris/plugins/configfilefilter/crypto/AESCrypto.java
> +
不支持的先抛个异常吧

2023-07-12 13:47 UTC, chuntaojun commented on polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/java/com/tencent/polaris/plugins/configfilefilter/CryptoConfigFileFilter.java
> +    public CryptoConfigFileFilter(Crypto crypto, RSAService rsaService, CryptoConfig cryptoConfig, Map<String, Crypto> cryptoMap) {
这个构造函数只是测试使用吗？是的话加一个 @JustForTesting

2023-07-17 08:04 UTC, SkyeBeFreeman approved these changes

2023-07-17 08:04 UTC, merged